version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ogn
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/100_init.sql
      - ./data/timescaledb:/var/lib/postgresql/data
      - ./data/ogn_logfiles:/mnt/ogn_logfiles
    command:  # we need these commands for pg_stat_statements
      - -cshared_preload_libraries=timescaledb,pg_stat_statements
      - -cpg_stat_statements.track=all
    networks:
      - monitoring

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5050:80}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - monitoring
  
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data/zeppelin/logs:/logs
      - ./data/zeppelin/notebook:/notebook
    #  - ./data/zeppelin/interpreter.json:/opt/zeppelin/conf/interpreter.json
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    #volumes:
    #  - ./data/grafana/dashboard:/etc/extra-config/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
