version: '3'

services:
  timescaledb:
    image: xbgmsharp/timescaledb-postgis:latest
    container_name: timescaledb
    restart: unless-stopped
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./sql/timescaledb-initdb:/docker-entrypoint-initdb.d
      - ${DOCKERVOLUMES}/timescaledb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 12
    command:
      - -cshared_preload_libraries=timescaledb,pg_stat_statements,pg_cron
      - -ccron.database_name=${POSTGRES_DB}
      - -cpg_stat_statements.track=all
    networks:
      - monitoring

  ogn:
    image: ogn-client-rs
    container_name: ogn
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - ${DOCKERVOLUMES}/ogn-logfiles:/ogn-logfiles
    restart: unless-stopped
    command: ogn-client --target postgre-sql --database-url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/${POSTGRES_DB}
    #restart: "no"
    #command: ["sh", "-c", "gzip -c -d /ogn-logfiles/stdout.log-20230325.gz | ogn-client --source stdin --target postgre-sql --database-url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/${POSTGRES_DB}"]
    networks:
      - monitoring
  
  ressources:
    image: ressources
    container_name: ressources
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DOCKERVOLUMES}/ressources:/ressources
    command: ["sh", "-c", "./entrypoint_update_once.sh && ./entrypoint_cron.sh"]
    networks:
      - monitoring

#  questdb:
#    image: questdb/questdb:6.7
#    container_name: questdb
#    restart: unless-stopped
#    ports:
#      - 9000:9000 # REST API and Web Console
#      - 9009:9009 # InfluxDB line protocol
#      - 8812:8812 # Postgres wire protocol
#      - 9003:9003 # Min health server
#    environment:
#      QDB_PG_USER: ${POSTGRES_USER}
#      QDB_PG_PASSWORD: ${POSTGRES_PASSWORD}
#      QDB_CAIRO_SQL_COPY_ROOT: /mnt/ogn_logfiles
#    volumes:
#      - ./data/questdb:/var/lib/questdb
#      - ./data/ogn_logfiles:/mnt/ogn_logfiles
#    networks:
#      - monitoring

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - timescaledb
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5050:80}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    user: "0"
    container_name: grafana
    depends_on:
      - timescaledb
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-worldmap-panel,pr0ps-trackmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'True'
      GF_SERVER_DOMAIN: 'localhost'
      GF_DATABASE_URL: 'postgres://grafana:password@timescaledb:5432/grafana'
      GF_PLUGINS_ENABLE_ALPHA: 'True'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - timescaledb
      - grafana
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
