# Rust as the base image
FROM rust:1.86-slim-bookworm AS builder

# Build the app
RUN apt update && \
    apt install -y git build-essential && \ 
    git clone https://github.com/Meisterschueler/ogn-client-rs.git && \
    cd ogn-client-rs && \
    cargo install --path .

# Create a small final image
FROM debian:bookworm-slim
COPY --from=builder /usr/local/cargo/bin/ogn-client /usr/local/bin/ogn-client

CMD ["ogn-client"]
