apiVersion: 1

# https://grafana.com/docs/grafana/latest/datasources/postgres/
datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: ${POSTGRES_DB}
    user: ${GRAFANA_READER_USER}
    isDefault: true
    secureJsonData:
      password: ${GRAFANA_READER_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenCons: 0 # eigentlich 'unlimited'
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
