{
 "title": "Receiver details",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sel_country",
    "label": "country",
    "query": "SELECT iso2 FROM receivers ORDER BY iso2"
   },
   {
    "name": "sel_receiver",
    "label": "receiver",
    "query": "SELECT name FROM receivers WHERE iso2 = '$sel_country'\nORDER BY name"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT LAST(cpu_temperature, ts)\nFROM statuses\nWHERE $__timeFilter(ts)\n  AND src_call = '$sel_receiver'"
    }
   ]
  },
  {
   "title": "enders signal quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT LAST(senders_signal_quality, ts)\nFROM statuses\nWHERE $__timeFilter(ts)\n  AND src_call = '$sel_receiver'"
    }
   ]
  },
  {
   "title": "good senders signal quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT LAST(good_senders_signal_quality, ts)\nFROM statuses\nWHERE $__timeFilter(ts)\n  AND src_call = '$sel_receiver'"
    }
   ]
  },
  {
   "title": "signal quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT LAST(signal_quality, ts)\r\nFROM statuses\r\nWHERE\r\n  $__timeFilter(ts)\r\n  AND src_call = '$sel_receiver'"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT ts, signal_quality, senders_signal_quality, good_senders_signal_quality\nFROM statuses\nWHERE $__timeFilter(ts) AND src_call = '$sel_receiver'"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts,\r\n  MAX(normalized_quality)\r\nFROM ranking_statistics_1d\r\nWHERE\r\n  $__timeFilter(ts)\r\n  AND receiver = '$sel_receiver'\r\nGROUP BY ts"
    }
   ]
  }
 ]
}