CREATE TABLE IF NOT EXISTS positions (
    "ts"                TIMESTAMP NOT NULL,
    src_call            STRING NOT NULL,
    dst_call            STRING NOT NULL,
    receiver            STRING NOT NULL,
    latitude            DOUBLE NOT NULL,
    longitude           DOUBLE NOT NULL,
    symbol_table        CHAR NOT NULL,
    symbol_code         CHAR NOT NULL,
    course              INT,
    speed               INT,
    altitude            INT,
    address_type        SHORT,
    aircraft_type       SHORT,
    is_stealth          BOOLEAN,
    is_notrack          BOOLEAN,
    address	            INT,
    climb_rate          INT,
    turn_rate           DOUBLE,
    error               SHORT,
    frequency_offset    DOUBLE,
    signal_quality      DOUBLE,
    gps_quality         STRING,
    flight_level        DOUBLE,
    signal_power        DOUBLE,
    software_version    DOUBLE,
    hardware_version    STRING,
    original_address    INT,
    comment             STRING,
    distance            DOUBLE,
    normalized_quality  DOUBLE
) TIMESTAMP(ts) PARTITION BY DAY;
