DROP TABLE IF EXISTS 'positions';
CREATE TABLE IF NOT EXISTS 'positions' (
  packet_ts         TIMESTAMP,
  receiver_ts       TIMESTAMP,
  src_call          STRING,
  dst_call          STRING,
  receiver          STRING,
  latitude          DOUBLE,
  longitude         DOUBLE,
  symbol_table      STRING,
  symbol_code       STRING,
  course            INT,
  speed             INT,
  altitude          INT,
  address_type      INT,
  aircraft_type     INT,
  is_stealth        BOOLEAN,
  is_notrack        BOOLEAN,
  address           STRING,
  climb_rate        INT,
  turn_rate         DOUBLE,
  error             INT,
  frequency_offset  DOUBLE,
  signal_quality    DOUBLE,
  gps_quality       STRING,
  flight_level      DOUBLE,
  signal_power      DOUBLE,
  software_version  DOUBLE,
  hardware_version  INT,
  real_id           STRING,
  comment           STRING,
  distance          DOUBLE,
  normalized_quality DOUBLE
) timestamp(packet_ts) PARTITION BY DAY;
COPY 'positions' FROM 'stdout.csv-20221228' WITH HEADER TRUE;