server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx/*log
  pipeline_stages:
    - json:
        expressions:
          time_local: time_local
          http_referer: http_referer
    - timestamp:
        source: time_local
        format: "2/Jan/2006:15:04:05 -0700"
    - regex:
        source: http_referer
        expression: 'var\-sel_country=(?P<country>[A-Za-z0-9]+)'
    - labels:
        country: country
    - regex:
        source: http_referer
        expression: 'var\-sel_airport=(?P<airport>[A-Za-z0-9\-%]+)'
    - labels:
        airport: airport
    - regex:
        source: http_referer
        expression: 'var\-sel_sender=(?P<sender>[A-Z0-9]+)'
    - labels:
        sender: sender
    - regex:
        source: http_referer
        expression: 'var\-sel_receiver=(?P<receiver>[A-Za-z0-9]+)'
    - labels:
        receiver: receiver

- job_name: timescaledb
  static_configs:
  - targets:
      - localhost
    labels:
      job: timescaledb
      __path__: /var/log/timescaledb/*json
  pipeline_stages:
    - json:
        expressions:
          timestamp: timestamp
    - timestamp:
        source: timestamp
        format: "2006-01-02 15:04:05.000 MST"
