server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx/*log
  pipeline_stages:
    - match:
        selector: '{job="nginx"}'
        stages:
        - regex:
            expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] \"(?P<method>[A-Z]+) (?P<path>\S+) (?P<http_version>[^\"]+)" (?P<status>\d+) (?P<bytes_sent>\d+) \"(?P<http_referer>[^\"]+)" "(?P<http_user_agent>[^\"]+)"$'
        - labels:
            remote_addr:
            remote_user:
            time_local:
            method:
            path:
            http_version:
            status:
            bytes_sent:
            http_referer:
            http_user_agent:

- job_name: timescaledb
  static_configs:
  - targets:
      - localhost
    labels:
      job: timescaledb
      __path__: /var/log/timescaledb/*log
  pipeline_stages:
    - match:
        selector: '{job="timescaledb"}'
        stages:
        - multiline:
            firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} UTC'
        - regex:
            expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) UTC (?P<message>(?s:.*))$'
        - labels:
            time:
            message:
