name: Build and run

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the docker images
        run: make

      - name: create .env file and set variables
        run: |
          cp .env.example .env
          sed -i 's|^DOCKERVOLUMES=.*|DOCKERVOLUMES=./dockervolumes|' .env

      - name: Create the directory for docker volumes
        run: mkdir -p ./dockervolumes

      - name: Show the docker compose configuration
        run: docker compose --env-file .env config

      - name: Start docker containers with docker compose (ignore exit code because timescaledb needs time to start)
        run: docker compose --env-file .env up -d || true

      - name: Wait for the containers to become healthy
        run: sleep 100

      - name: Show the status of the containers
        run: docker ps -a

      - name: Show the logs of the containers
        run: docker compose logs

      - name: Tear down docker compose
        if: always()
        run: docker compose down
