name: Build and run

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the docker images
        run: make

      - name: Start docker containers with docker compose (ignore exit code because timescaledb needs time to start)
        run: docker compose --env-file .env.example up -d || true

      - name: Wait for the containers to become healthy
        run: sleep 100

      - name: Show the status of the containers
        run: docker ps -a

      - name: Show the docker compose environment variables
        run: docker compose --env-file .env.example config || true

      - name: Show the docker compose configuration
        run: docker compose config --environment || true

      - name: Show the logs of the containers
        run: docker compose logs

      - name: Tear down docker compose
        if: always()
        run: docker compose down
