name: Build and Test with Docker Compose

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run make to build the docker images
        run: make

      - name: Start docker compose services
        run: docker compose --env-file .env.example up -d

      - name: Wait for services to become healthy (optional)
        run: sleep 100

      - name: Run tests (optional)
        run: docker compose exec -T service_name pytest tests/

      - name: Tear down docker compose
        if: always()
        run: docker compose down
